services:
  database:
    image: postgres
    container_name: s3_postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: busan_climate
    volumes:
      - database_data:/var/lib/postgresql/data
  
  dataviz:
    image: metabase/metabase
    container_name: s3_metabase
    ports:
      - 3001:3000
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: busan_climate
      MB_DB_PORT: 5432
      MB_DB_USER: postgres
      MB_DB_PASS: 1234
      MB_DB_HOST: database
      MB_DB_FILE: /metabase-data/busan_climate.db
    depends_on: 
      - database
    volumes:
      - dataviz_data:/metabase-data

volumes:
  database_data:
  dataviz_data: